Feat/rent bike
io2-2021-wed-brodka/G_Backend pull request #14
Opened 2021-04-17 16:48 UTC by KrolikJakub

Wypożyczanie rowerów plus oczywiście testy

2021-04-17 16:57 UTC, tomkarw commented on bikes/tests.py
> +        self.assertEqual(1, 1)
jeśli to jest dummy na przyszłość, to daj pass zamiast tego asserta

2021-04-17 17:37 UTC, linalenets approved these changes

2021-04-17 17:54 UTC, tomkarw requested changes

2021-04-17 17:54 UTC, tomkarw commented on bikes/views.py
> +            rented_bike.status = BikeStatus.rented
Sama zmiana pola obiektu nie zapisuje tego do bazy (modyfikujemy tylko read reprezentację obiektu w bazie). Trzeba zawsze pamiętać o 
```
rented_bike.save()
```

Dodatkowo, wypożyczony rower przestaje być przypisany do stacji, trzeba pole `rented_bike.station` ustawić na `None`.

Ostatecznie powinno to wyglądać tak:
```
rented_bike.status = BikeStatus.rented
rented_bike.station = None
rented_bike.save()
```

2021-04-17 17:54 UTC, tomkarw commented on bikes/views.py
> +        if rented_bike.user.username == "blocked":  # placeholder user is blocked
Pisanie kodu który nie ma prawa działać na zaś to mocny antipattern, nie rób tak nigdy proszę.
Zastąp to zakomentowanym blokiem kodu z obowiązkowym TODO (takie komentarze łatwo wyszukać potem w całym projekcie.

Moja propozycja
```
        # TODO(kkrolik): uncomment once blocking users is introduced
        # user = somehow_get_user_from_token_in_headers(request)
        # if user.status == UserStatus.blocked:
        #     return Response(
        #         {"message": "Blocked users are not allowed to rent bikes"},
        #         status=status.HTTP_403_FORBIDDEN,
        #     )
```

2021-04-17 17:54 UTC, tomkarw commented on bikes/views.py
> +            rented_bike.status = BikeStatus.rented
Dodatkowa sprawa, zabrakło testów które mogłyby to wyłapać, dodaj proszę takie dwa testy:
```
    def test_rent_bike_status_changes_to_rented(self):

    def test_rent_bike_station_changes_to_null(self):
```

2021-04-17 17:54 UTC, tomkarw commented on bikes/tests.py
> +    def test_rent_bike_user_blocked(self):
zróbmy ostatecznie tego TODOsa tutaj zamiast testu

```
# TODO(kkrolik): add test for blocked user renting when user blocking is introduced
```

2021-04-18 08:48 UTC, tomkarw approved these changes
Kuba, możesz już iść na Django Developera spokojnie.

2021-04-18 08:50 UTC, merged