[ROW-83] All /users endpoints
io2-2021-wed-brodka/G_Backend pull request #21
Opened 2021-04-22 19:19 UTC by tomkarw

2021-04-23 09:02 UTC, arkadiusz-gorecki requested changes

2021-04-23 09:02 UTC, arkadiusz-gorecki commented on users/views.py
> +                {"message": "Bike not reserved"},
Metoda `handle_exception` wygląda jakby została skopiowana bez żadnych zmian z bikes/views.py. Nie wiem do czego mają one służyć bo nigdzie nie są wywoływane. Chyba, że niejawnie to się wywołuje po wykryciu wyjątku.

2021-04-23 09:05 UTC, tomkarw commented on users/views.py
> +                {"message": "Bike not reserved"},
Tak jest, tutaj napisujemy część zachowań internalowych django, ale masz rację że nie zmieniłem message przy kopiowaniu.

2021-04-24 07:17 UTC, arkadiusz-gorecki approved these changes

2021-04-24 10:25 UTC, KrolikJakub approved these changes

2021-04-24 10:25 UTC, merged